# Default values for plugin-center.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: scmmanager/website
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: true
  annotations:
    kubernetes.io/tls-acme: "true"
    acme.cert-manager.io/http01-ingress-class: traefik
    traefik.ingress.kubernetes.io/router.middlewares: scm-manager-website-cors@kubernetescrd
  ingressClassName: traefik
  cors:
    name: website-cors
    namespace: scm-manager
    headers:
      accessControlAllowMethods:
        - GET
        - OPTIONS
      accessControlAllowHeaders:
        - DNT
        - X-CustomHeader
        - Keep-Alive
        - User-Agent
        - X-Requested-With
        - If-Modified-Since
        - Cache-Control
        - Content-Type
        - Authorization
      accessControlAllowOriginList:
        - "*"
      accessControlMaxAge: 100
      addVaryHeader: true
  hosts:
    - host: scm-manager.org
      paths:
        - /
    - host: www.scm-manager.org
      paths:
        - /

  tls:
    - secretName: website-tls
      hosts:
        - scm-manager.org
        - www.scm-manager.org

resources:
  limits:
    memory: 16Mi
  requests:
    cpu: 100m
    memory: 16Mi

nodeSelector: {}

tolerations: []

affinity: {}
