ingress:
  enabled: true
  annotations:
    kubernetes.io/tls-acme: "true"
    acme.cert-manager.io/http01-ingress-class: traefik
    traefik.ingress.kubernetes.io/router.middlewares: scm-manager-website-cors@kubernetescrd
  ingressClassName: traefik
  cors:
    name: website-cors
    namespace: scm-manager
    headers:
      accessControlAllowMethods:
        - GET
        - OPTIONS
      accessControlAllowHeaders:
        - DNT
        - X-CustomHeader
        - Keep-Alive
        - User-Agent
        - X-Requested-With
        - If-Modified-Since
        - Cache-Control
        - Content-Type
        - Authorization
      accessControlAllowOriginList:
        - "*"
      accessControlMaxAge: 100
      addVaryHeader: true
  hosts:
    - host: staging-website.scm-manager.org
      paths:
        - /

  tls:
    - secretName: staging-website-tls
      hosts:
        - staging-website.scm-manager.org
